### ISSUE TITLE
Explorer crashed after switch to Win32 mode

### ISSUE THREAD

**Issue by liziyu0714** [liziyu0714/FishDeskNextReborn#1]
**Describe the bug**
Sometimes explorer.exe crashed after switch to Win32 mode

**To Reproduce**
1.Launch FDNR
2. Click on 'Switch to Win32 mode'
3. Crash!!!

**Comment by scetayh** [comment]
Emmm... Reproduction Step 3 is so funny(

**Comment by liziyu0714** [comment]
The function will be rewrited using fsw workload.
